language: node_js
node_js:
- "10"
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
  - GH_USER_NAME: rghorbani
  - GH_PROJECT_NAME: react-native-general-calendars
  - GH_FULL_NAME: Reza Ghorbani Farid
  - GH_EMAIL: r.ghorbani.f@gmail.com
  - SITE_URL: https://rghorbani.ir
  - GH_REF: github.com/rghorbani/react-native-persian-calendar-picker/
install:
- yarn
